services:
  solarwatch-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  solarwatchapp:
    image: solarwatchapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - solarwatch-db
    environment:
      ASPNETCORE_CONNECTIONSTRING: ${ASPNETCORE_CONNECTIONSTRING}

  solarwatch-frontend:
      build:
        context: .
        dockerfile: ../SolarWatchFrontend/solar-watch-frontend/Dockerfile
      ports:
        - "3000:3000"
